-- Band Manager — Show Operations v13
-- Logística do evento + checklist operacional compartilhado.
-- IDs externos continuam TEXT para não acoplar esta feature ao tipo físico
-- (uuid/bigint/text) das tabelas antigas.

create table if not exists public.evento_operacao (
  org_id text not null,
  evento_id text not null,
  chegada_em timestamptz,
  passagem_som_em timestamptz,
  endereco text,
  mapa_url text,
  contato_nome text,
  contato_telefone text,
  observacoes text,
  updated_by text,
  updated_at timestamptz not null default now(),
  primary key (org_id, evento_id)
);

create index if not exists evento_operacao_event_idx
  on public.evento_operacao (evento_id);

create table if not exists public.evento_checklist (
  id bigint generated by default as identity primary key,
  org_id text not null,
  evento_id text not null,
  titulo text not null,
  categoria text not null default 'outro'
    check (categoria in ('equipamento', 'palco', 'logistica', 'outro')),
  concluido boolean not null default false,
  ordem integer not null default 0,
  responsavel_membro_id text,
  concluido_por text,
  concluido_em timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists evento_checklist_event_order_idx
  on public.evento_checklist (org_id, evento_id, ordem, id);

create index if not exists evento_checklist_responsavel_idx
  on public.evento_checklist (org_id, responsavel_membro_id, evento_id);

comment on table public.evento_operacao is
  'Informações compartilhadas de logística do show: chegada, passagem, endereço, contato e observações.';

comment on table public.evento_checklist is
  'Checklist compartilhado da banda por evento, com categoria, responsável e registro de conclusão.';
