-- Band Manager — Smart Repertoire & Show Prep v8
-- Migration funcional para estatísticas permanentes, músicas fixadas e notas pessoais.
-- IDs são armazenados como TEXT de propósito para não depender do tipo atual
-- (uuid/bigint/text) usado nas tabelas existentes do projeto.

create table if not exists public.repertorio_execucoes (
  id bigint generated by default as identity primary key,
  org_id text not null,
  evento_id text,
  repertorio_id text not null,
  membro_id text,
  origem text not null default 'setlist' check (origem in ('setlist', 'request')),
  titulo text,
  artista text,
  categoria text,
  tom text,
  bpm integer,
  played_at timestamptz not null default now()
);

create index if not exists repertorio_execucoes_org_played_idx
  on public.repertorio_execucoes (org_id, played_at desc);

create index if not exists repertorio_execucoes_song_idx
  on public.repertorio_execucoes (org_id, repertorio_id, played_at desc);

create index if not exists repertorio_execucoes_event_idx
  on public.repertorio_execucoes (org_id, evento_id, played_at asc);

create table if not exists public.repertorio_live_favoritos (
  org_id text not null,
  repertorio_id text not null,
  pinned_at timestamptz not null default now(),
  primary key (org_id, repertorio_id)
);

create index if not exists repertorio_live_favoritos_org_idx
  on public.repertorio_live_favoritos (org_id, pinned_at desc);

create table if not exists public.repertorio_notas_membro (
  org_id text not null,
  repertorio_id text not null,
  membro_id text not null,
  nota text not null default '',
  updated_at timestamptz not null default now(),
  primary key (org_id, repertorio_id, membro_id)
);

create index if not exists repertorio_notas_membro_lookup_idx
  on public.repertorio_notas_membro (org_id, membro_id, repertorio_id);

comment on table public.repertorio_execucoes is
  'Histórico permanente de músicas efetivamente iniciadas no Live. Alimenta Mais tocadas, Mais pedidas e Recentes.';

comment on table public.repertorio_live_favoritos is
  'Músicas fixadas pela banda no topo da Troca Rápida.';

comment on table public.repertorio_notas_membro is
  'Anotações pessoais de palco por integrante e música.';
