-- Band Manager — Versioning & Recovery v10
-- Histórico de versões da arquitetura musical.
-- O snapshot é JSONB para preservar título, metadados, blocos, acordes posicionados
-- e ordem da timeline sem acoplar o histórico aos IDs físicos que são recriados ao salvar.

create table if not exists public.repertorio_versoes (
  id bigint generated by default as identity primary key,
  org_id text not null,
  repertorio_id text not null,
  motivo text not null default 'before_save',
  membro_id text,
  membro_nome text,
  snapshot jsonb not null,
  created_at timestamptz not null default now()
);

create index if not exists repertorio_versoes_song_created_idx
  on public.repertorio_versoes (org_id, repertorio_id, created_at desc);

comment on table public.repertorio_versoes is
  'Backups automáticos da música antes de cada gravação. O restore carrega o snapshot no editor e exige uma nova gravação explícita.';
